/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bd2.DBConnect;
import java.awt.Container;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.time.LocalDateTime;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author s.jantos
 */
public class JFrameMakeWarehouseOrder extends javax.swing.JFrame {
    DBConnect connect;
    Container mainPane;
    int width;
    int loggedEmployee;
//    'YYYY-MM-DD'
    
    /**
     * Creates new form JFrameMakeClientOrder
     */
    public JFrameMakeWarehouseOrder(DBConnect con, int empID) {
        initComponents();
        connect = con;
        loggedEmployee = empID;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textBoxProviderID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textBoxDrinkID1 = new javax.swing.JTextField();
        textBoxDrinkID2 = new javax.swing.JTextField();
        textBoxDrinkID3 = new javax.swing.JTextField();
        textBoxDrinkID4 = new javax.swing.JTextField();
        textBoxDrinkID5 = new javax.swing.JTextField();
        textBoxDrinkID6 = new javax.swing.JTextField();
        textBoxDrinkID7 = new javax.swing.JTextField();
        textBoxDrinkID8 = new javax.swing.JTextField();
        textBoxDrinkID9 = new javax.swing.JTextField();
        textBoxDrinkID10 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textBoxQuantity1 = new javax.swing.JTextField();
        textBoxQuantity2 = new javax.swing.JTextField();
        textBoxQuantity3 = new javax.swing.JTextField();
        textBoxQuantity4 = new javax.swing.JTextField();
        textBoxQuantity5 = new javax.swing.JTextField();
        textBoxQuantity6 = new javax.swing.JTextField();
        textBoxQuantity7 = new javax.swing.JTextField();
        textBoxQuantity8 = new javax.swing.JTextField();
        textBoxQuantity9 = new javax.swing.JTextField();
        textBoxQuantity10 = new javax.swing.JTextField();
        buttonMakeClientOrder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Provider ID");

        jLabel2.setText("Drink ID");

        jLabel3.setText("Quantity");

        buttonMakeClientOrder.setText("Order");
        buttonMakeClientOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMakeClientOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textBoxProviderID, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(textBoxDrinkID1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3))
                                    .addComponent(textBoxDrinkID2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textBoxDrinkID3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textBoxDrinkID4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textBoxDrinkID5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textBoxDrinkID6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textBoxDrinkID7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textBoxDrinkID9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textBoxDrinkID8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textBoxDrinkID10, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textBoxQuantity10, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textBoxQuantity9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textBoxQuantity8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textBoxQuantity7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textBoxQuantity6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textBoxQuantity5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textBoxQuantity4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textBoxQuantity3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textBoxQuantity2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textBoxQuantity1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(buttonMakeClientOrder)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textBoxProviderID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textBoxDrinkID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(textBoxQuantity1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBoxDrinkID2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBoxQuantity2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBoxDrinkID3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBoxQuantity3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBoxDrinkID4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBoxQuantity4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBoxDrinkID5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBoxQuantity5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBoxDrinkID6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBoxQuantity6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBoxDrinkID7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBoxQuantity7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBoxDrinkID9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBoxQuantity8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBoxDrinkID8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBoxQuantity9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBoxDrinkID10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBoxQuantity10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(buttonMakeClientOrder)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonMakeClientOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMakeClientOrderActionPerformed
        // TODO add your handling code here:
        StringBuilder date = new StringBuilder();
        LocalDateTime dateTime = LocalDateTime.now();
        date.append(dateTime.getYear());
        date.append("-");
        date.append(dateTime.getMonthValue());
        date.append("-");
        date.append(dateTime.getDayOfMonth());
        int providerID = Integer.parseInt(textBoxProviderID.getText());
        LinkedList productIDs = new LinkedList();
        if(!textBoxDrinkID1.getText().isEmpty())
            productIDs.add(Integer.parseInt(textBoxDrinkID1.getText()));
        if(!textBoxDrinkID2.getText().isEmpty())
            productIDs.add(Integer.parseInt(textBoxDrinkID2.getText()));
        if(!textBoxDrinkID3.getText().isEmpty())
            productIDs.add(Integer.parseInt(textBoxDrinkID3.getText()));
        if(!textBoxDrinkID4.getText().isEmpty())
            productIDs.add(Integer.parseInt(textBoxDrinkID4.getText()));
        if(!textBoxDrinkID5.getText().isEmpty())
            productIDs.add(Integer.parseInt(textBoxDrinkID5.getText()));
        if(!textBoxDrinkID6.getText().isEmpty())
            productIDs.add(Integer.parseInt(textBoxDrinkID6.getText()));
        if(!textBoxDrinkID7.getText().isEmpty())
            productIDs.add(Integer.parseInt(textBoxDrinkID7.getText()));
        if(!textBoxDrinkID8.getText().isEmpty())
            productIDs.add(Integer.parseInt(textBoxDrinkID8.getText()));
        if(!textBoxDrinkID9.getText().isEmpty())
            productIDs.add(Integer.parseInt(textBoxDrinkID9.getText()));
        if(!textBoxDrinkID10.getText().isEmpty())
            productIDs.add(Integer.parseInt(textBoxDrinkID10.getText()));
        
        LinkedList productQuantities = new LinkedList();
        if(!textBoxQuantity1.getText().isEmpty())
            productQuantities.add(Integer.parseInt(textBoxQuantity1.getText()));
        if(!textBoxQuantity2.getText().isEmpty())
            productQuantities.add(Integer.parseInt(textBoxQuantity2.getText()));
        if(!textBoxQuantity3.getText().isEmpty())
            productQuantities.add(Integer.parseInt(textBoxQuantity3.getText()));
        if(!textBoxQuantity4.getText().isEmpty())
            productQuantities.add(Integer.parseInt(textBoxQuantity4.getText()));
        if(!textBoxQuantity5.getText().isEmpty())
            productQuantities.add(Integer.parseInt(textBoxQuantity5.getText()));
        if(!textBoxQuantity6.getText().isEmpty())
            productQuantities.add(Integer.parseInt(textBoxQuantity6.getText()));
        if(!textBoxQuantity7.getText().isEmpty())
            productQuantities.add(Integer.parseInt(textBoxQuantity7.getText()));
        if(!textBoxQuantity8.getText().isEmpty())
            productQuantities.add(Integer.parseInt(textBoxQuantity8.getText()));
        if(!textBoxQuantity9.getText().isEmpty())
            productQuantities.add(Integer.parseInt(textBoxQuantity9.getText()));
        if(!textBoxQuantity10.getText().isEmpty())
            productQuantities.add(Integer.parseInt(textBoxQuantity10.getText()));
        
        int warehouseOrderID = -1;
        try {
            Connection con = connect.getConnection();
            CallableStatement myStmt = con.prepareCall("SELECT * FROM warehouseOrders");
            myStmt.execute();
            ResultSet result = myStmt.getResultSet();
            int lastID = 0;
            while(result.next())
                lastID++;
            warehouseOrderID = ++lastID;
        } catch (Exception e) {
            System.out.println("ERROR szukanie ostatniego ID");
            Logger.getLogger(DBConnect.class.getName()).log(Level.SEVERE, null, e);
        }
        
        try {
            Connection con = connect.getConnection();
            CallableStatement myStmt = con.prepareCall("{call MakeWarehouseOrder(?,?,?,?,?)}");
        myStmt.setString(1,date.toString());
        myStmt.setBoolean(2,false);
        myStmt.setInt(3,1);
        myStmt.setInt(4,providerID);
        myStmt.setInt(5,loggedEmployee);
        myStmt.execute();
        } catch (Exception e) {
            System.out.println("ERROR dodawanie zamowienia");
            Logger.getLogger(DBConnect.class.getName()).log(Level.SEVERE, null, e);
        }
        
        for (int i = 0; i < productIDs.size(); i++) {
            try {
            Connection con = connect.getConnection();
            CallableStatement myStmt = con.prepareCall("{call AddOrderedWarehouseProduct(?,?,?)}");
            myStmt.setInt(1,warehouseOrderID);
            myStmt.setInt(2,(int)productIDs.get(i));
            myStmt.setInt(3,(int)productQuantities.get(i));
            myStmt.execute();
        } catch (Exception e) {
            System.out.println("ERROR dodawanie produktow do zamowienia");
            Logger.getLogger(DBConnect.class.getName()).log(Level.SEVERE, null, e);
        }
        }
        
        end();
    }//GEN-LAST:event_buttonMakeClientOrderActionPerformed
public void end()
    {
        setVisible(false);
        dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonMakeClientOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField textBoxDrinkID1;
    private javax.swing.JTextField textBoxDrinkID10;
    private javax.swing.JTextField textBoxDrinkID2;
    private javax.swing.JTextField textBoxDrinkID3;
    private javax.swing.JTextField textBoxDrinkID4;
    private javax.swing.JTextField textBoxDrinkID5;
    private javax.swing.JTextField textBoxDrinkID6;
    private javax.swing.JTextField textBoxDrinkID7;
    private javax.swing.JTextField textBoxDrinkID8;
    private javax.swing.JTextField textBoxDrinkID9;
    private javax.swing.JTextField textBoxProviderID;
    private javax.swing.JTextField textBoxQuantity1;
    private javax.swing.JTextField textBoxQuantity10;
    private javax.swing.JTextField textBoxQuantity2;
    private javax.swing.JTextField textBoxQuantity3;
    private javax.swing.JTextField textBoxQuantity4;
    private javax.swing.JTextField textBoxQuantity5;
    private javax.swing.JTextField textBoxQuantity6;
    private javax.swing.JTextField textBoxQuantity7;
    private javax.swing.JTextField textBoxQuantity8;
    private javax.swing.JTextField textBoxQuantity9;
    // End of variables declaration//GEN-END:variables
}
