package gui;

import bd2.DBConnect;
import javax.swing.JFrame;
import net.proteanit.sql.DbUtils;

public class JFrameSeller extends javax.swing.JFrame {
    JFrame frame;
    DBConnect connect;
    int loggedEmployeeID;
    /**
     * Creates new form JFrameManager
     * @param con
     * @param employeeID
     */
    public JFrameSeller(DBConnect con, int employeeID) {
        initComponents();
        frame = this;
        connect = con;
        loggedEmployeeID = employeeID;
        table.setModel(DbUtils.resultSetToTableModel(connect.ShowClientOrders()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelOptions = new javax.swing.JPanel();
        buttonSearch = new javax.swing.JButton();
        buttonMakeClientOrder = new javax.swing.JButton();
        buttonCancelClientOrder = new javax.swing.JButton();
        buttonAddClient = new javax.swing.JButton();
        buttonEdit = new javax.swing.JButton();
        panelViews = new javax.swing.JPanel();
        buttonClientOrders = new javax.swing.JButton();
        buttonWarehouseOrders = new javax.swing.JButton();
        buttonClients = new javax.swing.JButton();
        buttonProviders = new javax.swing.JButton();
        buttonDrinks = new javax.swing.JButton();
        scrollpanel = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.BorderLayout());

        panelOptions.setLayout(new java.awt.GridLayout(5, 0));

        buttonSearch.setText("Wyszukaj");
        buttonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearchActionPerformed(evt);
            }
        });
        panelOptions.add(buttonSearch);

        buttonMakeClientOrder.setText("Złóż zamówienie klienta");
        panelOptions.add(buttonMakeClientOrder);

        buttonCancelClientOrder.setText("Anuluj zamówienie klienta");
        panelOptions.add(buttonCancelClientOrder);

        buttonAddClient.setText("Dodaj klienta");
        panelOptions.add(buttonAddClient);

        buttonEdit.setText("Edytuj");
        panelOptions.add(buttonEdit);

        getContentPane().add(panelOptions, java.awt.BorderLayout.LINE_START);

        buttonClientOrders.setText("Show client orders");
        buttonClientOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClientOrdersActionPerformed(evt);
            }
        });
        panelViews.add(buttonClientOrders);

        buttonWarehouseOrders.setText("Show warehouse orders");
        buttonWarehouseOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonWarehouseOrdersActionPerformed(evt);
            }
        });
        panelViews.add(buttonWarehouseOrders);

        buttonClients.setText("Show clients");
        buttonClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClientsActionPerformed(evt);
            }
        });
        panelViews.add(buttonClients);

        buttonProviders.setText("Show providers");
        buttonProviders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProvidersActionPerformed(evt);
            }
        });
        panelViews.add(buttonProviders);

        buttonDrinks.setText("Show drinks");
        buttonDrinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDrinksActionPerformed(evt);
            }
        });
        panelViews.add(buttonDrinks);

        getContentPane().add(panelViews, java.awt.BorderLayout.PAGE_START);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollpanel.setViewportView(table);

        getContentPane().add(scrollpanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonClientOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClientOrdersActionPerformed
        table.setModel(DbUtils.resultSetToTableModel(connect.ShowClientOrders()));
    }//GEN-LAST:event_buttonClientOrdersActionPerformed

    private void buttonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchActionPerformed
        JFrameSearch searchFrame = new JFrameSearch(table, frame);
        
        searchFrame.setVisible(true);
        System.out.println(searchFrame.isVisible());
    }//GEN-LAST:event_buttonSearchActionPerformed

    private void buttonDrinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDrinksActionPerformed
        table.setModel(DbUtils.resultSetToTableModel(connect.ShowAllDrinks()));
    }//GEN-LAST:event_buttonDrinksActionPerformed

    private void buttonWarehouseOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonWarehouseOrdersActionPerformed
        table.setModel(DbUtils.resultSetToTableModel(connect.ShowWarehouseOrders()));
    }//GEN-LAST:event_buttonWarehouseOrdersActionPerformed

    private void buttonClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClientsActionPerformed
        table.setModel(DbUtils.resultSetToTableModel(connect.ShowAllClients()));
    }//GEN-LAST:event_buttonClientsActionPerformed

    private void buttonProvidersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProvidersActionPerformed
        table.setModel(DbUtils.resultSetToTableModel(connect.ShowAllProviders()));
    }//GEN-LAST:event_buttonProvidersActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddClient;
    private javax.swing.JButton buttonCancelClientOrder;
    private javax.swing.JButton buttonClientOrders;
    private javax.swing.JButton buttonClients;
    private javax.swing.JButton buttonDrinks;
    private javax.swing.JButton buttonEdit;
    private javax.swing.JButton buttonMakeClientOrder;
    private javax.swing.JButton buttonProviders;
    private javax.swing.JButton buttonSearch;
    private javax.swing.JButton buttonWarehouseOrders;
    private javax.swing.JPanel panelOptions;
    private javax.swing.JPanel panelViews;
    private javax.swing.JScrollPane scrollpanel;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
