/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bd2.DBConnect;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author s.jantos
 */
public class JFrameCancelWarehouseOrder extends javax.swing.JFrame {
    DBConnect connect;
    /**
     * Creates new form JFrameCancelClientOrder
     */
    public JFrameCancelWarehouseOrder(DBConnect con) {
        initComponents();
        connect = con;
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textBoxOrderIDToCancel = new javax.swing.JTextField();
        buttonCancelWarehouseOrder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Warehuose order ID to cancel");

        buttonCancelWarehouseOrder.setText("OK");
        buttonCancelWarehouseOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelWarehouseOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(textBoxOrderIDToCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCancelWarehouseOrder))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textBoxOrderIDToCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonCancelWarehouseOrder)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCancelWarehouseOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelWarehouseOrderActionPerformed
        // TODO add your handling code here:
        boolean dataCorrect = true;
        int orderID = -1;
        try {
            orderID = Integer.parseInt(textBoxOrderIDToCancel.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Bledne dane.","Error", JOptionPane.ERROR_MESSAGE);
            dataCorrect = false;
        }
        
        if(dataCorrect)
        {
            try {
            Connection con = connect.getConnection();
            CallableStatement myStmt = con.prepareCall("{CALL CancelWarehouseOrder(?)}");
            myStmt.setInt(1, orderID);
            myStmt.execute();
        } catch (Exception e) {
            System.out.println("ERROR szukanie ostatniego ID");
            Logger.getLogger(DBConnect.class.getName()).log(Level.SEVERE, null, e);
        }
        }
        
        end();
    }//GEN-LAST:event_buttonCancelWarehouseOrderActionPerformed

public void end()
    {
        setVisible(false);
        dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancelWarehouseOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField textBoxOrderIDToCancel;
    // End of variables declaration//GEN-END:variables
}
