package gui;

import bd2.DBConnect;
import javax.swing.JFrame;
import net.proteanit.sql.DbUtils;

public class JFrameManager extends javax.swing.JFrame {
    JFrame frame;
    DBConnect connect;
    int loggedEmployeeID;
    /**
     * Creates new form JFrameManager
     * @param con
     * @param employeeID
     */
    public JFrameManager(DBConnect con, int employeeID) {
        initComponents();
        frame = this;
        connect = con;
        loggedEmployeeID = employeeID;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelOptions = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        panelViews = new javax.swing.JPanel();
        buttonClientOrders = new javax.swing.JButton();
        buttonWarehouseOrders = new javax.swing.JButton();
        buttonClients = new javax.swing.JButton();
        buttonProviders = new javax.swing.JButton();
        buttonDrinks = new javax.swing.JButton();
        scrollpanel = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelOptions.setLayout(new java.awt.GridBagLayout());

        jButton6.setText("jButton6");
        panelOptions.add(jButton6, new java.awt.GridBagConstraints());

        jButton7.setText("jButton7");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        panelOptions.add(jButton7, gridBagConstraints);

        jButton8.setText("jButton8");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        panelOptions.add(jButton8, gridBagConstraints);

        jButton9.setText("jButton9");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        panelOptions.add(jButton9, gridBagConstraints);

        jButton10.setText("jButton10");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        panelOptions.add(jButton10, gridBagConstraints);

        getContentPane().add(panelOptions, java.awt.BorderLayout.LINE_START);

        buttonClientOrders.setText("Show client orders");
        buttonClientOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClientOrdersActionPerformed(evt);
            }
        });
        panelViews.add(buttonClientOrders);

        buttonWarehouseOrders.setText("Show warehouse orders");
        panelViews.add(buttonWarehouseOrders);

        buttonClients.setText("Show clients");
        panelViews.add(buttonClients);

        buttonProviders.setText("Show providers");
        panelViews.add(buttonProviders);

        buttonDrinks.setText("Show drinks");
        panelViews.add(buttonDrinks);

        getContentPane().add(panelViews, java.awt.BorderLayout.PAGE_START);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollpanel.setViewportView(table);

        getContentPane().add(scrollpanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonClientOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClientOrdersActionPerformed
        table.setModel(DbUtils.resultSetToTableModel(connect.ShowClientOrders()));
    }//GEN-LAST:event_buttonClientOrdersActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonClientOrders;
    private javax.swing.JButton buttonClients;
    private javax.swing.JButton buttonDrinks;
    private javax.swing.JButton buttonProviders;
    private javax.swing.JButton buttonWarehouseOrders;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel panelOptions;
    private javax.swing.JPanel panelViews;
    private javax.swing.JScrollPane scrollpanel;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
