/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.GridLayout;
import java.awt.Label;
import java.util.LinkedList;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Jantos
 */
public class JFrameSearch extends javax.swing.JFrame {
    JTable table;
    LinkedList<JTextField> textFields;
    JFrame parent;
    /**
     * Creates new form JFrameSearch
     */
    public JFrameSearch(JTable table, JFrame frame) {
        initComponents();
        parent = frame;
        int numberOfColumns = table.getColumnCount();
        panelSearchOptions.setLayout(new GridLayout(2*numberOfColumns, 1, 4, 4));
        textFields = new LinkedList<JTextField>();
        for (int i = 0; i < 2*numberOfColumns; i++) {
            if(i%2 == 1)
            {
                panelSearchOptions.add(new Label(table.getColumnName(i/2)), i-1);
            }
            else
            {
                textFields.add(new JTextField());
                panelSearchOptions.add(textFields.getLast(), i);
            }
        }
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSearchOptions = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelSearchOptionsLayout = new javax.swing.GroupLayout(panelSearchOptions);
        panelSearchOptions.setLayout(panelSearchOptionsLayout);
        panelSearchOptionsLayout.setHorizontalGroup(
            panelSearchOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        panelSearchOptionsLayout.setVerticalGroup(
            panelSearchOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        getContentPane().add(panelSearchOptions, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelSearchOptions;
    // End of variables declaration//GEN-END:variables
}
